window.WAUBUG_MODULES = {
  navigation: ["connect", "pwd", "ls", "cd", "tree"],
  analysis: ["cat", "find", "grep", "decode", "brief", "triage", "hint", "intel", "victims"],
  containment: ["quarantine", "submit", "status", "missions"],
  utilities: ["help", "clear", "leaderboard", "savepoint", "report", "board", "resetlab", "history", "whoami", "matrix", "exit", "start", "accept"],
};

window.WAUBUG_HELP = [
  "CASE NAVIGATION:",
  "connect [node]             Switch between simulated nodes",
  "pwd                        Show current path",
  "ls [-a] [path]             List directory contents, hidden with -a",
  "cd [path]                  Change directory",
  "tree [-a] [path]           Render directory tree",
  "",
  "FORENSICS:",
  "cat [file]                 Read a file",
  "find [term]                Search for names in the current node",
  "grep [term] [path]         Search file contents recursively",
  "decode [base64|hex] [str]  Decode clue fragments",
  "brief                      Show the case briefing",
  "triage                     Show live objectives and discovered evidence",
  "hint                       Reveal the next hint and lose score",
  "intel                      Show the next likely move",
  "victims                    Show the virtual victim roster",
  "",
  "CONTAINMENT:",
  "quarantine [artifact]      Quarantine invoice-lock or lensync",
  "submit victim [name]       Submit the victim identity",
  "submit key [token]         Submit the final unlock token",
  "status                     Show case status",
  "missions                   Show the case arc",
  "",
  "UTILITY:",
  "leaderboard                Show local case leaderboard",
  "savepoint                  Save local progress",
  "report                     Export a local report",
  "board                      Open the evidence board",
  "resetlab confirm           Reset the entire case",
  "history                    Show recent commands",
  "help                       Show this menu",
];
